line-length = 100

[lint]

# https://docs.astral.sh/ruff/rules
select = [
    "E4",   # pycodestyle
    "E7",
    "E9",
    "F",    # pyflakes
    "PL",   # pylint
]

ignore = [
    "PLR0911",  # too-many-return-statements
    "PLR0915",  # too-many-statements
    "PLR2004",  # magic-value-comparison
    "PLW2901",  # redefined-loop-name
]
